export const GENDERS = [
  { id: 'male', label: 'Male' },
  { id: 'female', label: 'Female' },
  { id: 'other', label: 'Other' },
];

export const RASHIS = [
  { name: 'Mesha', nameTa: 'மேஷம்' },
  { name: 'Vrishabha', nameTa: 'ரிஷபம்' },
  { name: 'Mithuna', nameTa: 'மிதுனம்' },
  { name: 'Karka', nameTa: 'கடகம்' },
  { name: 'Simha', nameTa: 'சிம்மம்' },
  { name: 'Kanya', nameTa: 'கன்னி' },
  { name: 'Tula', nameTa: 'துலாம்' },
  { name: 'Vrishchika', nameTa: 'விருச்சிகம்' },
  { name: 'Dhanu', nameTa: 'தனுசு' },
  { name: 'Makara', nameTa: 'மகரம்' },
  { name: 'Kumbha', nameTa: 'கும்பம்' },
  { name: 'Meena', nameTa: 'மீனம்' },
];

export const NAKSHATRAS = [
  { name: 'Ashwini', nameTa: 'அசுவினி' },
  { name: 'Bharani', nameTa: 'பரணி' },
  { name: 'Krittika', nameTa: 'கிருத்திகை' },
  { name: 'Rohini', nameTa: 'ரோகிணி' },
  { name: 'Mrigashira', nameTa: 'மிருகசீரிடம்' },
  { name: 'Ardra', nameTa: 'திருவாதிரை' },
  { name: 'Punarvasu', nameTa: 'புனர்பூசம்' },
  { name: 'Pushya', nameTa: 'பூசம்' },
  { name: 'Ashlesha', nameTa: 'ஆயில்யம்' },
  { name: 'Magha', nameTa: 'மகம்' },
  { name: 'Purva Phalguni', nameTa: 'பூரம்' },
  { name: 'Uttara Phalguni', nameTa: 'உத்திரம்' },
  { name: 'Hasta', nameTa: 'அஸ்தம்' },
  { name: 'Chitra', nameTa: 'சித்திரை' },
  { name: 'Swati', nameTa: 'சுவாதி' },
  { name: 'Vishakha', nameTa: 'விசாகம்' },
  { name: 'Anuradha', nameTa: 'அனுஷம்' },
  { name: 'Jyeshtha', nameTa: 'கேட்டை' },
  { name: 'Mula', nameTa: 'மூலம்' },
  { name: 'Purva Ashadha', nameTa: 'பூராடம்' },
  { name: 'Uttara Ashadha', nameTa: 'உத்திராடம்' },
  { name: 'Shravana', nameTa: 'திருவோணம்' },
  { name: 'Dhanishta', nameTa: 'அவிட்டம்' },
  { name: 'Shatabhisha', nameTa: 'சதயம்' },
  { name: 'Purva Bhadrapada', nameTa: 'பூரட்டாதி' },
  { name: 'Uttara Bhadrapada', nameTa: 'உத்திரட்டாதி' },
  { name: 'Revati', nameTa: 'ரேவதி' },
];

export const PLACES = [
  'Ahmedabad',
  'Bengaluru',
  'Bhopal',
  'Chandigarh',
  'Chennai',
  'Coimbatore',
  'Delhi',
  'Hyderabad',
  'Indore',
  'Jaipur',
  'Kochi',
  'Kolkata',
  'Lucknow',
  'Mumbai',
  'Nagpur',
  'Patna',
  'Pune',
  'Surat',
  'Thiruvananthapuram',
  'Visakhapatnam',
];

export const PLACE_COORDS: Record<string, { lat: number; lon: number }> = {
  Ahmedabad: { lat: 23.0225, lon: 72.5714 },
  Bengaluru: { lat: 12.9716, lon: 77.5946 },
  Bhopal: { lat: 23.2599, lon: 77.4126 },
  Chandigarh: { lat: 30.7333, lon: 76.7794 },
  Chennai: { lat: 13.0827, lon: 80.2707 },
  Coimbatore: { lat: 11.0168, lon: 76.9558 },
  Delhi: { lat: 28.6139, lon: 77.209 },
  Erode: { lat: 11.341, lon: 77.717 },
  Hyderabad: { lat: 17.385, lon: 78.4867 },
  Indore: { lat: 22.7196, lon: 75.8577 },
  Jaipur: { lat: 26.9124, lon: 75.7873 },
  Kochi: { lat: 9.9312, lon: 76.2673 },
  Kolkata: { lat: 22.5726, lon: 88.3639 },
  Lucknow: { lat: 26.8467, lon: 80.9462 },
  Mumbai: { lat: 19.076, lon: 72.8777 },
  Nagpur: { lat: 21.1458, lon: 79.0882 },
  Patna: { lat: 25.5941, lon: 85.1376 },
  Pune: { lat: 18.5204, lon: 73.8567 },
  Surat: { lat: 21.1702, lon: 72.8311 },
  Thiruvananthapuram: { lat: 8.5241, lon: 76.9366 },
  Visakhapatnam: { lat: 17.6868, lon: 83.2185 },
};
