import type { AppLanguage } from './i18n';

/**
 * UI STRINGS — en / தமிழ் / हिन्दी
 * --------------------------------
 * Screen text for Tamil & Hindi users. Calculation engines never use these.
 * Use: const t = uiStrings(language);  then  t.home.title  etc.
 */

type Dict = Record<string, string>;

const en: Dict = {
  // Login
  'login.welcome': 'Welcome to Koshmira',
  'login.subtitle': 'Sign in with Google to begin your cosmic journey',
  'login.google': 'Continue with Google',
  'login.tagline': 'Your daily guide to the stars',
  'login.privacy': 'By continuing you agree to our Terms & Privacy Policy',
  // Home
  'home.quickActions': 'Quick Actions',
  'home.horoscope': "Today's Horoscope",
  'home.topAstrologers': 'Top Astrologers',
  'home.luckyWindow': 'Lucky window',
  'home.chat': 'Chat',
  'home.yrs': 'yrs',
  // Tabs
  'tab.home': 'Home',
  'tab.chat': 'Chat',
  'tab.astrologer': 'Astrologer',
  'tab.palm': 'Palm Reading',
  'tab.account': 'Account',
  // Match
  'match.title': 'Match Making',
  'match.history': 'History',
  'match.groom': 'Groom',
  'match.bride': 'Bride',
  'match.name': 'Name',
  'match.dob': 'Date of Birth',
  'match.tob': 'Time of Birth',
  'match.place': 'Birth Place',
  'match.manual': 'I know my star',
  'match.auto': 'Birth Date & Time',
  'match.selectRasi': 'Select Moon Sign (Rasi)',
  'match.selectNak': 'Select Birth Star (Nakshatra)',
  'match.rasiFirst': 'Select Rasi first',
  'match.check': 'Check Compatibility',
  'match.report': 'Match Report',
  'match.poruthamOf': 'of 10 Porutham matched',
  // Palm UI
  'palm.title': 'Palm Reading',
  'palm.subtitle': 'Uncover your destiny in your palm',
  'palm.manual': 'Manual',
  'palm.import': 'Import',
  'palm.scanning': 'Reading...',
  'palm.handDetected': 'Hand detected — tap Manual to capture',
  'palm.placePalm': 'Place your open palm in the frame',
  'palm.noHand': 'No hand detected. Please try again.',
  'palm.permNeeded': 'Camera Access Needed',
  'palm.permDesc': 'Allow camera access to scan your palm and reveal your reading',
  'palm.allow': 'Allow Camera',
  'palm.camUnavailable': 'Camera Unavailable',
  'palm.camDesc': 'The camera is blocked on this device. Try a different device or check settings.',
  'palm.retry': 'Retry',
  'palm.resultTitle': 'Your Palm Analysis',
  'palm.lines': 'Line Readings',
  'palm.traits': 'Personality Traits',
  'palm.metrics': 'Hand Geometry',
  'palm.done': 'Done',
  'palm.disclaimer': 'This reading is based on ancient Vedic palmistry traditions passed down through generations of learned scholars.',
  'palm.askTitle': 'Ask about your reading',
  'palm.askHint': 'Type a question about your palm reading...',
  'palm.send': 'Send',
  'palm.suggest1': 'What does my life line mean?',
  'palm.suggest2': 'Tell me about my career',
  'palm.suggest3': 'How is my love life?',
  'palm.suggest4': 'What are my strengths?',
  // Palm — line readings EN
  'palm.life.strong': 'Life line: long and deeply etched — strong vitality, resilience and a warm constitution.',
  'palm.life.steady': 'Life line: clear and steady — balanced energy; protect it with routine and rest.',
  'palm.life.sensitive': 'Life line: lighter chain-like breaks — sensitive energy; recovery time matters for you.',
  'palm.heart.passionate': 'Heart line: rising boldly toward Jupiter mount — passionate, protective in love; you commit intensely.',
  'palm.heart.devoted': 'Heart line: deep and gently curved — steady affection, loyalty and emotional intelligence.',
  'palm.heart.balanced': 'Heart line: even and harmonious — you love through friendship first, then deep attachment.',
  'palm.head.analytical': 'Head line: long and slightly sloped — analytical, methodical mind; you think before you leap.',
  'palm.head.practical': 'Head line: clear and well-balanced — practical intelligence with quick common sense.',
  'palm.head.intuitive': 'Head line: short and decisive — instinct-led thinker; fast judgments, fast action.',
  'palm.fate.craft': 'Fate line: broad and grounded — hands-on career growth; success through craft and consistency.',
  'palm.fate.creative': 'Fate line: fine and rising — creative or advisory calling; unconventional path rewards you.',
  'palm.fate.leader': 'Fate line: straight and supported — dependable progress; leadership roles find you mid-life.',
  'palm.comm.persuasive': 'Little finger stands tall — persuasive speech; teaching, sales or media suit you.',
  'palm.comm.trusted': 'Little finger well-placed — clear communicator; people trust your words.',
  'palm.comm.listener': 'Little finger modest — you speak less but mean more; written words favour you.',
  // Palm — traits EN
  'palm.trait.stamina': 'High stamina',
  'palm.trait.energy': 'Steady energy',
  'palm.trait.sensitive': 'Sensitive system',
  'palm.trait.passionate': 'Passionate heart',
  'palm.trait.devoted': 'Devoted partner',
  'palm.trait.balanced': 'Balanced heart',
  'palm.trait.analytical': 'Analytical mind',
  'palm.trait.practical': 'Practical thinker',
  'palm.trait.intuitive': 'Quick intuition',
  'palm.trait.craft': 'Master of craft',
  'palm.trait.creative': 'Creative path',
  'palm.trait.leader': 'Natural leader',
  'palm.trait.persuasive': 'Persuasive voice',
  'palm.trait.trusted': 'Trusted words',
  'palm.trait.listener': 'Deep listener',
  // Trust
  'trust.disclaimer':
    'Predictions are traditional astrological interpretations, not guarantees or scientific facts. Please use your own judgment for important decisions.',
  'home.nallaNeram': 'Nalla Neram (Auspicious Time)',
  'home.rahuKalam': 'Rahu Kalam',
  'home.share': 'Share on WhatsApp',
  'home.palm': 'Palm Reading',
  'chat.search': 'Search astrologers...',
  'chat.available': 'Available now',
  'chat.lastSeen': 'Last seen',
  'astrologer.search': 'Search by name...',
  'astrologer.sortRating': 'Top Rated',
  'astrologer.sortExperience': 'Most Experienced',
  'astrologer.pricing': 'Consultation Fee',
  'astrologer.online': 'Online',
  'account.whatsapp': 'Share on WhatsApp',
  'account.deleteAccount': 'Delete Account',
  'account.about': 'About Koshmira',
  'account.share': 'Share App',
  'palm.leftHand': 'Left Hand (Destiny)',
  'palm.rightHand': 'Right Hand (Effort)',
  'palm.guideTitle': 'How to Place Your Palm',
  'palm.guide1': 'Hold your hand flat and open',
  'palm.guide2': 'Keep fingers together and straight',
  'palm.guide3': 'Place palm facing the camera',
  'palm.guide4': 'Ensure good lighting on your palm',
  'palm.whatsapp': 'Share on WhatsApp',
  'palm.disclaimerTitle': 'Disclaimer',
  'tarot.past': 'Past',
  'tarot.present': 'Present',
  'tarot.future': 'Future',
  'tarot.viewReading': 'View Full Reading',
  'tarot.history': 'Reading History',
  'match.papaDosham': 'Papa Dosham Check',
  'onboarding.step1Title': 'Tell us who you are',
  'onboarding.step2Title': 'Your date and time of birth',
  'onboarding.step3Title': 'Where were you born?',
  'onboarding.gothram': 'Gothram (Lineage)',
  'onboarding.gothramHint': 'Enter your family Gothram',
  'onboarding.finish': 'Finish',
  'horoscope.luckyNumber': 'Lucky Number',
  'horoscope.luckyColor': 'Lucky Color',
  'horoscope.remedy': 'Remedy',
  'horoscope.weekly': 'Weekly Horoscope',
  'horoscope.monthly': 'Monthly Horoscope',
  'kundli.download': 'Download PDF',
  'kundli.share': 'Share Chart',
  'jathagam.rahuKalam': 'Rahu Kalam',
  'jathagam.gulikai': 'Gulikai',
  'jathagam.sectionJump': 'Jump to section',
  'login.phone': 'Login with Phone',
  'login.guest': 'Continue as Guest',
};

const ta: Dict = {
  'login.welcome': 'Koshmira-க்கு வரவேற்கிறோம்',
  'login.subtitle': 'உங்கள் ஜோதிடப் பயணத்தை தொடங்க Google-உடன் உள்நுழையுங்கள்',
  'login.google': 'Google-உடன் தொடரவும்',
  'login.tagline': 'நட்சத்திரங்களின் தினசரி வழிகாட்டி',
  'login.privacy': 'தொடர்வதன் மூலம் எங்கள் விதிமுறைகளை ஏற்கிறீர்கள்',
  'home.quickActions': 'விரைவு செயல்பாடுகள்',
  'home.horoscope': 'இன்றைய ராசி பலன்',
  'home.topAstrologers': 'முன்னணி ஜோதிடர்கள்',
  'home.luckyWindow': 'நல்ல நேரம்',
  'home.chat': 'அரட்டை',
  'home.yrs': 'வயது',
  'tab.home': 'முகப்பு',
  'tab.chat': 'அரட்டை',
  'tab.astrologer': 'ஜோதிடர்',
  'tab.palm': 'கைரேகை',
  'tab.account': 'கணக்கு',
  'match.title': 'திருமண பொருத்தம்',
  'match.history': 'வரலாறு',
  'match.groom': 'மணமகன்',
  'match.bride': 'மணமகள்',
  'match.name': 'பெயர்',
  'match.dob': 'பிறந்த தேதி',
  'match.tob': 'பிறந்த நேரம்',
  'match.place': 'பிறந்த இடம்',
  'match.manual': 'நட்சத்திரம் தெரியும்',
  'match.auto': 'பிறந்த தேதி & நேரம்',
  'match.selectRasi': 'ராசியைத் தேர்ந்தெடுங்கள்',
  'match.selectNak': 'நட்சத்திரத்தைத் தேர்ந்தெடுங்கள்',
  'match.rasiFirst': 'முதலில் ராசியைத் தேர்ந்தெடுங்கள்',
  'match.check': 'பொருத்தம் சரிபார்க்க',
  'match.report': 'பொருத்த அறிக்கை',
  'match.poruthamOf': '/10 பொருத்தம் பொருந்தியது',
  // Palm UI TA
  'palm.title': 'கைரேகை',
  'palm.subtitle': 'உங்கள் கையில் உங்கள் விதியை கண்டறியுங்கள்',
  'palm.manual': 'கைமுறை',
  'palm.import': 'படம் சேர்',
  'palm.scanning': 'படிக்கிறது...',
  'palm.handDetected': 'கை கண்டறியப்பட்டது — கைமுறை என்பதை அழுத்தவும்',
  'palm.placePalm': 'உங்கள் திறந்த கையை சட்டத்தில் வைக்கவும்',
  'palm.noHand': 'கை கண்டறியப்படவில்லை. மீண்டும் முயற்சிக்கவும்.',
  'palm.permNeeded': 'கேமரா அனுமதி தேவை',
  'palm.permDesc': 'உங்கள் கையை ஸ்கேன் செய்ய கேமரா அனுமதியை அனுமதிக்கவும்',
  'palm.allow': 'கேமரா அனுமதி',
  'palm.camUnavailable': 'கேமரா கிடைக்கவில்லை',
  'palm.camDesc': 'இந்த சாதனத்தில் கேமரா தடுக்கப்பட்டுள்ளது.',
  'palm.retry': 'மீண்டும் முயற்சி',
  'palm.resultTitle': 'உங்கள் கைரேகை பகுப்பாய்வு',
  'palm.lines': 'கோட்டு பலன்கள்',
  'palm.traits': 'ஆளுமை குணங்கள்',
  'palm.metrics': 'கை அளவியல்',
  'palm.done': 'முடிந்தது',
  'palm.disclaimer': 'இந்த பலன் பல தலைமுறை அறிஞர்களால் கற்பிக்கப்பட்ட பண்டைய வேத கைரேகை மரபுகளின் அடிப்படையில் அமைந்துள்ளது.',
  'palm.askTitle': 'உங்கள் பலன் பற்றி கேளுங்கள்',
  'palm.askHint': 'உங்கள் கைரேகை பற்றி ஒரு கேள்வி உள்ளிடவும்...',
  'palm.send': 'அனுப்பு',
  'palm.suggest1': 'என் உயிர்க் கோடு என்ன சொல்கிறது?',
  'palm.suggest2': 'என் தொழில் பற்றி சொல்லுங்கள்',
  'palm.suggest3': 'என் காதல் வாழ்வு எப்படி?',
  'palm.suggest4': 'என் பலங்கள் என்ன?',
  // Palm — line readings TA
  'palm.life.strong': 'உயிர்க் கோடு: நீளமாகவும் ஆழமாகவும் — வலுவான உயிர்ப்பு, தாங்கும் திறன், உடல் ஆரோக்கியம்.',
  'palm.life.steady': 'உயிர்க் கோடு: தெளிவாகவும் நிலையாகவும் — சமநிலை ஆற்றல்; வழக்கம் மற்றும் ஓய்வு தேவை.',
  'palm.life.sensitive': 'உயிர்க் கோடு: இலேசான சங்கிலி போன்ற இடைவெளிகள் — உணர்திறன் ஆற்றல்; மீட்சி நேரம் முக்கியம்.',
  'palm.heart.passionate': 'இதயக் கோடு: குரு மேடு நோக்கி தைரியமாக உயர்கிறது — காதலில் உணர்ச்சிமிக்க, பாதுகாப்பான; தீவிரமாக கடமைப்படுகிறீர்கள்.',
  'palm.heart.devoted': 'இதயக் கோடு: ஆழமாகவும் மெதுவாகவும் வளைந்தது — நிலையான அன்பு, விசுவாசம், உணர்வு நுண்ணறிவு.',
  'palm.heart.balanced': 'இதயக் கோடு: சமநிலையாகவும் இனிமையாகவும் — நட்பு முதலில், பின்னர் ஆழமான பிணைப்பு.',
  'palm.head.analytical': 'தலைக் கோடு: நீளமாகவும் சிறிது சாய்ந்ததும் — பகுப்பாய்வு, முறையான மனம்; சிந்தித்து செயல்படுகிறீர்கள்.',
  'palm.head.practical': 'தலைக் கோடு: தெளிவாகவும் நன்கு சமநிலையாகவும் — நடைமுறை நுண்ணறிவு, விரைவு புத்திசாலித்தனம்.',
  'palm.head.intuitive': 'தலைக் கோடு: குறுகியதும் தீர்மானமானதும் — உள்ளுணர்வு சிந்தனையாளர்; விரைவு முடிவுகள்.',
  'palm.fate.craft': 'விதிக் கோடு: அகலமாகவும் நிலத்தில் நிலைத்ததும் — கைவினை திறன் மூலம் வெற்றி; உறுதியான முன்னேற்றம்.',
  'palm.fate.creative': 'விதிக் கோடு: நுண்ணியதும் உயர்ந்ததும் — படைப்பு அல்லது ஆலோசனை அழைப்பு; மாற்று வழியில் வெற்றி.',
  'palm.fate.leader': 'விதிக் கோடு: நேராகவும் ஆதரவாகவும் — நம்பகமான முன்னேற்றம்; நடுப்பருவத்தில் தலைமை பாத்திரங்கள்.',
  'palm.comm.persuasive': 'சிறிய விரல் உயரமாக நிற்கிறது — சமர்த்தமான பேச்சு; கற்பித்தல், விற்பனை அல்லது ஊடகம் ஏற்றது.',
  'palm.comm.trusted': 'சிறிய விரல் நன்கு நிலைநிறுத்தப்பட்டது — தெளிவான தொடர்பாளர்; மக்கள் உங்கள் வார்த்தைகளை நம்புகிறார்கள்.',
  'palm.comm.listener': 'சிறிய விரல் சிறியது — குறைவாக பேசுகிறீர்கள் ஆனால் அதிகம் சொல்கிறீர்கள்; எழுத்து வார்த்தைகள் சாதகமாக உள்ளன.',
  // Palm — traits TA
  'palm.trait.stamina': 'அதிக சகிப்புத்திறன்',
  'palm.trait.energy': 'நிலையான ஆற்றல்',
  'palm.trait.sensitive': 'உணர்திறன்',
  'palm.trait.passionate': 'உணர்ச்சிமிக்க இதயம்',
  'palm.trait.devoted': 'அர்ப்பணிப்புள்ள துணை',
  'palm.trait.balanced': 'சமநிலை இதயம்',
  'palm.trait.analytical': 'பகுப்பாய்வு மனம்',
  'palm.trait.practical': 'நடைமுறை சிந்தனையாளர்',
  'palm.trait.intuitive': 'விரைவு உள்ளுணர்வு',
  'palm.trait.craft': 'கைவினை திறன்',
  'palm.trait.creative': 'படைப்பு பாதை',
  'palm.trait.leader': 'இயல்பான தலைவர்',
  'palm.trait.persuasive': 'சமர்த்தமான குரல்',
  'palm.trait.trusted': 'நம்பகமான வார்த்தைகள்',
  'palm.trait.listener': 'ஆழமான கேட்பவர்',
  // Trust
  'trust.disclaimer':
    'இவை அனைத்தும் பாரம்பரிய ஜோதிட விளக்கங்களே — உத்தரவாதங்கள் அல்ல, அறிவியல் உண்மைகளும் அல்ல. முக்கியமான முடிவுகளை உங்கள் சொந்த விவேகத்துடன் எடுக்கவும்.',
  'home.nallaNeram': 'நல்ல நேரம்',
  'home.rahuKalam': 'ராகு காலம்',
  'home.share': 'WhatsApp இல் பகிர்',
  'home.palm': 'கைரேகை',
  'chat.search': 'ஜோதிடரைத் தேடுங்கள்...',
  'chat.available': 'இப்போது கிடைக்கிறது',
  'chat.lastSeen': 'கடைசியாக பார்த்தது',
  'astrologer.search': 'பெயரால் தேடுங்கள்...',
  'astrologer.sortRating': 'சிறந்த மதிப்பீடு',
  'astrologer.sortExperience': 'அதிக அனுபவம்',
  'astrologer.pricing': 'ஆலோசனை கட்டணம்',
  'astrologer.online': 'ஆன்லைன்',
  'account.whatsapp': 'WhatsApp இல் பகிர்',
  'account.deleteAccount': 'கணக்கை நீக்கு',
  'account.about': 'Koshmira பற்றி',
  'account.share': 'ஆப்பை பகிர்',
  'palm.leftHand': 'இடது கை (விதி)',
  'palm.rightHand': 'வலது கை (முயற்சி)',
  'palm.guideTitle': 'உங்கள் கையை எப்படி வைப்பது',
  'palm.guide1': 'உங்கள் கையை திறந்து தட்டையாக வைக்கவும்',
  'palm.guide2': 'விரல்களை ஒன்றாக நேராக வைக்கவும்',
  'palm.guide3': 'கையை கேமராவை நோக்கி வைக்கவும்',
  'palm.guide4': 'உங்கள் கையில் நல்ல ஒளி இருக்க வேண்டும்',
  'palm.whatsapp': 'WhatsApp இல் பகிர்',
  'palm.disclaimerTitle': 'மறுப்பு',
  'tarot.past': 'கடந்த காலம்',
  'tarot.present': 'நிகழ்காலம்',
  'tarot.future': 'எதிர்காலம்',
  'tarot.viewReading': 'முழு பலனைக் காண',
  'tarot.history': 'பலன் வரலாறு',
  'match.papaDosham': 'பாப்பா தோஷம் சரிபார்ப்பு',
  'onboarding.step1Title': 'உங்களைப் பற்றி சொல்லுங்கள்',
  'onboarding.step2Title': 'உங்கள் பிறந்த தேதி & நேரம்',
  'onboarding.step3Title': 'நீங்கள் எங்கே பிறந்தீர்கள்?',
  'onboarding.gothram': 'குலம் (Gothram)',
  'onboarding.gothramHint': 'உங்கள் குடும்ப குலத்தை உள்ளிடவும்',
  'onboarding.finish': 'முடி',
  'horoscope.luckyNumber': 'அதிர்ஷ்ட எண்',
  'horoscope.luckyColor': 'அதிர்ஷ்ட நிறம்',
  'horoscope.remedy': 'பரிகாரம்',
  'horoscope.weekly': 'வாராந்திர ராசி பலன்',
  'horoscope.monthly': 'மாதாந்திர ராசி பலன்',
  'kundli.download': 'PDF பதிவிறக்கம்',
  'kundli.share': 'சார்ட்டைப் பகிர்',
  'jathagam.rahuKalam': 'ராகு காலம்',
  'jathagam.gulikai': 'குளிகை',
  'jathagam.sectionJump': 'பிரிவுக்குச் செல்',
  'login.phone': 'ஃபோன் மூலம் உள்நுழை',
  'login.guest': 'விருந்தினராகத் தொடர்',
};

const hi: Dict = {
  'login.welcome': 'Koshmira में आपका स्वागत है',
  'login.subtitle': 'अपनी ज्योतिष यात्रा शुरू करने के लिए Google से साइन इन करें',
  'login.google': 'Google से जारी रखें',
  'login.tagline': 'सितारों की दुनिया में आपका दैनिक मार्गदर्शक',
  'login.privacy': 'जारी रखने से आप हमारी शर्तें और गोपनीयता नीति स्वीकार करते हैं',
  'home.quickActions': 'त्वरित विकल्प',
  'home.horoscope': 'आज का राशिफल',
  'home.topAstrologers': 'शीर्ष ज्योतिषी',
  'home.luckyWindow': 'शुभ समय',
  'home.chat': 'चैट',
  'home.yrs': 'वर्ष',
  'tab.home': 'होम',
  'tab.chat': 'चैट',
  'tab.astrologer': 'ज्योतिषी',
  'tab.palm': 'हस्तरेखा',
  'tab.account': 'खाता',
  'match.title': 'गुण मिलान',
  'match.history': 'इतिहास',
  'match.groom': 'वर',
  'match.bride': 'वधू',
  'match.name': 'नाम',
  'match.dob': 'जन्म तिथि',
  'match.tob': 'जन्म समय',
  'match.place': 'जन्म स्थान',
  'match.manual': 'मेरा नक्षत्र पता है',
  'match.auto': 'जन्म तिथि और समय',
  'match.selectRasi': 'राशि चुनें',
  'match.selectNak': 'नक्षत्र चुनें',
  'match.rasiFirst': 'पहले राशि चुनें',
  'match.check': 'मिलान जाँचें',
  'match.report': 'मिलान रिपोर्ट',
  'match.poruthamOf': '/10 गुण मेल खाए',
  // Palm UI HI
  'palm.title': 'हस्तरेखा',
  'palm.subtitle': 'अपनी हथेली में अपनी किस्मत खोजें',
  'palm.manual': 'मैनुअल',
  'palm.import': 'तस्वीर जोड़ें',
  'palm.scanning': 'पढ़ रहा है...',
  'palm.handDetected': 'हाथ मिला — मैनुअल दबाएं',
  'palm.placePalm': 'अपनी खुली हथेली फ्रेम में रखें',
  'palm.noHand': 'हाथ नहीं मिला। फिर से कोशिश करें।',
  'palm.permNeeded': 'कैमरा अनुमति आवश्यक',
  'palm.permDesc': 'अपनी हथेली स्कैन करने के लिए कैमरा अनुमति दें',
  'palm.allow': 'कैमरा अनुमति दें',
  'palm.camUnavailable': 'कैमरा उपलब्ध नहीं',
  'palm.camDesc': 'इस डिवाइस में कैमरा ब्लॉक है।',
  'palm.retry': 'पुनः प्रयास',
  'palm.resultTitle': 'आपकी हस्तरेखा विश्लेषण',
  'palm.lines': 'रेखा विश्लेषण',
  'palm.traits': 'व्यक्तित्व लक्षण',
  'palm.metrics': 'हथेली माप',
  'palm.done': 'हो गया',
  'palm.disclaimer': 'यह रीडिंग पीढ़ियों के विद्वानों द्वारा सिखाई गई प्राचीन वैदिक हस्तरेखा परंपराओं पर आधारित है।',
  'palm.askTitle': 'अपनी पढ़ाई के बारे में पूछें',
  'palm.askHint': 'अपनी हस्तरेखा के बारे में प्रश्न लिखें...',
  'palm.send': 'भेजें',
  'palm.suggest1': 'मेरी जीवन रेखा का क्या मतलब है?',
  'palm.suggest2': 'मेरे करियर के बारे में बताएं',
  'palm.suggest3': 'मेरी प्रेम जीवन कैसा है?',
  'palm.suggest4': 'मेरी ताकतें क्या हैं?',
  // Palm — line readings HI
  'palm.life.strong': 'जीवन रेखा: लंबी और गहरी — मजबूत जीवन शक्ति, सहनशक्ति, अच्छा स्वास्थ्य।',
  'palm.life.steady': 'जीवन रेखा: स्पष्ट और स्थिर — संतुलित ऊर्जा; दिनचर्या और आराम जरूरी।',
  'palm.life.sensitive': 'जीवन रेखा: हल्की श्रृंखला जैसी — संवेदनशील ऊर्जा; ठीक होने में समय लगता है।',
  'palm.heart.passionate': 'हृदय रेखा: गुरु पर्वत की ओर साहसी — प्रेम में जुनूनी, सुरक्षात्मक; गहरी प्रतिबद्धता।',
  'palm.heart.devoted': 'हृदय रेखा: गहरी और मुड़ी हुई — स्थिर स्नेह, वफादारी, भावनात्मक बुद्धिमत्ता।',
  'palm.heart.balanced': 'हृदय रेखा: संतुलित और सामंजस्यपूर्ण — पहले दोस्ती, फिर गहरा बंधन।',
  'palm.head.analytical': 'मस्तिष्क रेखा: लंबी और थोड़ी झुकी — विश्लेषणात्मक, व्यवस्थित दिमाग; सोच-समझकर कदम।',
  'palm.head.practical': 'मस्तिष्क रेखा: स्पष्ट और संतुलित — व्यावहारिक बुद्धि, त्वरित समझ।',
  'palm.head.intuitive': 'मस्तिष्क रेखा: छोटी और निर्णायक — अंतर्ज्ञान-संचालित; तेज निर्णय, तेज कार्रवाई।',
  'palm.fate.craft': 'भाग्य रेखा: चौड़ी और जमीन से जुड़ी — शिल्प से सफलता; लगातार प्रगति।',
  'palm.fate.creative': 'भाग्य रेखा: सूक्ष्म और ऊपर की ओर — रचनात्मक या सलाहकार मार्ग; अपरंपरागत रास्ता।',
  'palm.fate.leader': 'भाग्य रेखा: सीधी और समर्थित — भरोसेमंद प्रगति; मध्य आयु में नेतृत्व भूमिकाएं।',
  'palm.comm.persuasive': 'छोटी उंगली ऊंची — सम्मोहक वाणी; शिक्षण, बिक्री या मीडिया उपयुक्त।',
  'palm.comm.trusted': 'छोटी उंगली अच्छी — स्पष्ट संवाद; लोग आपकी बात पर भरोसा करते हैं।',
  'palm.comm.listener': 'छोटी उंगली छोटी — कम बोलते हैं लेकिन गहरा कहते हैं; लिखित शब्द बेहतर।',
  // Palm — traits HI
  'palm.trait.stamina': 'मजबूत सहनशक्ति',
  'palm.trait.energy': 'स्थिर ऊर्जा',
  'palm.trait.sensitive': 'संवेदनशील तंत्रिका',
  'palm.trait.passionate': 'जुनूनी हृदय',
  'palm.trait.devoted': 'समर्पित साथी',
  'palm.trait.balanced': 'संतुलित हृदय',
  'palm.trait.analytical': 'विश्लेषणात्मक दिमाग',
  'palm.trait.practical': 'व्यावहारिक सोच',
  'palm.trait.intuitive': 'त्वरित अंतर्ज्ञान',
  'palm.trait.craft': 'शिल्प माहिर',
  'palm.trait.creative': 'रचनात्मक मार्ग',
  'palm.trait.leader': 'स्वाभाविक नेता',
  'palm.trait.persuasive': 'प्रभावशाली वाणी',
  'palm.trait.trusted': 'भरोसेमंद शब्द',
  'palm.trait.listener': 'गहरा श्रोता',
  // Trust
  'trust.disclaimer':
    'ये सभी परंपरागत ज्योतिषीय व्याख्याएँ हैं — कोई गारंटी या वैज्ञानिक तथ्य नहीं। महत्वपूर्ण निर्णय अपने विवेक से लें।',
  'home.nallaNeram': 'Nalla Neram (Auspicious Time)',
  'home.rahuKalam': 'Rahu Kalam',
  'home.share': 'Share on WhatsApp',
  'home.palm': 'Palm Reading',
  'chat.search': 'Search astrologers...',
  'chat.available': 'Available now',
  'chat.lastSeen': 'Last seen',
  'astrologer.search': 'Search by name...',
  'astrologer.sortRating': 'Top Rated',
  'astrologer.sortExperience': 'Most Experienced',
  'astrologer.pricing': 'Consultation Fee',
  'astrologer.online': 'Online',
  'account.whatsapp': 'Share on WhatsApp',
  'account.deleteAccount': 'Delete Account',
  'account.about': 'About Koshmira',
  'account.share': 'Share App',
  'palm.leftHand': 'Left Hand (Destiny)',
  'palm.rightHand': 'Right Hand (Effort)',
  'palm.guideTitle': 'How to Place Your Palm',
  'palm.guide1': 'Hold your hand flat and open',
  'palm.guide2': 'Keep fingers together and straight',
  'palm.guide3': 'Place palm facing the camera',
  'palm.guide4': 'Ensure good lighting on your palm',
  'palm.whatsapp': 'WhatsApp पर साझा करें',
  'palm.disclaimerTitle': 'अस्वीकरण',
  'tarot.past': 'Past',
  'tarot.present': 'Present',
  'tarot.future': 'Future',
  'tarot.viewReading': 'View Full Reading',
  'tarot.history': 'Reading History',
  'match.papaDosham': 'Papa Dosham Check',
  'onboarding.step1Title': 'Tell us who you are',
  'onboarding.step2Title': 'Your date and time of birth',
  'onboarding.step3Title': 'Where were you born?',
  'onboarding.gothram': 'Gothram (Lineage)',
  'onboarding.gothramHint': 'Enter your family Gothram',
  'onboarding.finish': 'Finish',
  'horoscope.luckyNumber': 'Lucky Number',
  'horoscope.luckyColor': 'Lucky Color',
  'horoscope.remedy': 'Remedy',
  'horoscope.weekly': 'Weekly Horoscope',
  'horoscope.monthly': 'Monthly Horoscope',
  'kundli.download': 'Download PDF',
  'kundli.share': 'Share Chart',
  'jathagam.rahuKalam': 'Rahu Kalam',
  'jathagam.gulikai': 'Gulikai',
  'jathagam.sectionJump': 'Jump to section',
  'login.phone': 'Login with Phone',
  'login.guest': 'Continue as Guest',
};

const TABLES: Record<AppLanguage, Dict> = { en, ta, hi };

export function uiStrings(lang: AppLanguage): Dict & { t: (key: string) => string } {
  const table = TABLES[lang] ?? en;
  const out = { ...table } as Dict & { t?: (key: string) => string };
  out.t = (key: string) => table[key] ?? en[key] ?? key;
  return out as Dict & { t: (key: string) => string };
}

/** Trust disclaimer shown wherever predictions are displayed. */
export function trustDisclaimer(lang: AppLanguage): string {
  return TABLES[lang]?.['trust.disclaimer'] ?? en['trust.disclaimer'];
}
